### ISSUE TITLE
Investigate failure to self-route

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire-services#4]
@0pcom reported that routes from local SOCKS client to SOCKS server failed consistently. Since this is an edge case we may have missed in the implementation of services we need to investigate the following steps:

1. What route (if any) is the route finder returning when we request it to self-route
2. What is the setup node doing with this request and why does it fail

If the route finder does not return any route, that would make sense and possibly be the desired response. In that case we could just implement direct loopback as we do with dmsg right now on the route level.

If the route finder returns a route with hops to a remote node and then back, we need to figure out why that setup fails and if the setup node is producing errors or if the visor errors.

TODO: add logs of errors encountered when self-routing with SOCKS server
TODO: verify its not a SOCKS specific error by trying the same with helloworld app or Skychat

**Comment by 0pcom** [comment]
```
skywire-cli proxy start $(skywire-cli visor pk)
```
```
[2023-05-12T12:36:15.116721726-05:00] DEBUG [transport_manager]: Error dialing transport to 02cf226af53dc6e507dc12a7a444b76d9aa7bfbd48b5f83a8124af76e14f78e39a via sudph: mt.client.Dial: handshake failed: invalid character 'g' looking for beginning of value
```

02cf226af53dc6e507dc12a7a444b76d9aa7bfbd48b5f83a8124af76e14f78e39a is the local visor's public key

**Comment by mrpalide** [comment]
Everything is OK with dmsg transport.
